version: '3'
    
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=polisiga
      - POSTGRES_USER=polisiga
      - POSTGRES_PASSWORD=polisiga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: