# Generated by Django 2.2.14 on 2020-11-09 01:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0007_auto_20201014_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Estudiante',
        ),
    ]
